Project 1: Mobile version homepage
Fikerte-T/Fikerte-Portfolio pull request #1
Opened 2021-08-12 13:42 UTC by Fikerte-T

In this project I:

- Created a portfolio website home page using HTML, CSS (Flexbox, Images) using a template on Figma.
- Added HTML file
- Added CSS file focusing especially on Flexbox and Images
- Added HTML&CSS linter

2021-08-12 16:16 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️

### Hello @Fikerte-T ✋🏼  Your project is great. You are almost done. However there are some issues you should fix. Please fix them then your project will be approved.

### 💯  Nice to have 💯
 
- Your git flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️
- You stick to the design.✔️
- You know how to use flexbox very well.✔️
- You use HTML semantic elements correctly.✔️

### ♻️ Request changes ♻️


- [ ] _**Check the comments under the review.**_

### Optional suggestions

#### These are optional but highly recommended.

- [ ] For DRY css you should combine duplicate properties. Example, you can create class `.d-flex { display: flex}` and use this class in HTML file.

- [More information about DRY principles](https://www.freecodecamp.org/news/7-important-tips-for-writing-better-css/) 

- [Html and css best practices in curriculum](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)


### Cheers and Happy coding! 💻 👏
![almost](https://media.giphy.com/media/3ohzAj9sRN1Ehl06Gc/giphy.gif)

___
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2021-08-12 16:16 UTC, ahmetbozaci commented on index.html
> +        <a href="#"><i class="fas fa-bars"></i></a>
- [ ] Nice to create links. Also wrap this links by `nav` tag. Keep it `header` tag.

2021-08-12 16:16 UTC, ahmetbozaci commented on index.html
> +        <h2>I'm Fikerte Glad to see you!</h2>
- [ ] You can change the `h2` tag with `h1` tag. It is good for seo. [What is the H1 Tag and Why it is Important for SEO ](https://www.reliablesoft.net/h1-tag/#:~:text=The%20HTML%20tag%20is%20the%20first%20header%20tag%20visible,rest%20of%20the%20page%20tags.)

2021-08-12 16:16 UTC, ahmetbozaci commented on index.html
> +        </section>
- [ ] The list of icons has a `ul` tag (instead of `section`) to group them, and `li` per icon; each icon has a link (`a` tag). Please change it.

2021-08-12 16:16 UTC, ahmetbozaci commented on style.css
> +  display: flex;
**OPTIONAL**
- [ ] For DRY css you should combine duplicate properties. Example, you can create class `.d-flex { display: flex}` and use this class in HTML file.

- [More information about DRY principles](https://www.freecodecamp.org/news/7-important-tips-for-writing-better-css/) 

- [Html and css best practices in curriculum](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)

2021-08-12 22:03 UTC, safafa requested changes
## STATUS: CHANGES REQUESTED ♻️ 

Hi @Fikerte-T , Good job working on some of the changes requested by the previous reviewer 👏🏼 👏🏼 

Due to the changes,  you have small problems that you need to fix for the project to be approved.

## Required changes :

Check the inline comments.

## Optional changes :
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- I think It's always good to have a live demo link in the readme file.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-12 22:03 UTC, safafa commented on index.html
> +        </nav>
- [ ] Well done on using the `<nav>` tag. However, this created a little problem that needs to be solved for the project to be approved. 
![image](https://user-images.githubusercontent.com/43698511/129274915-4d2ebad4-d6da-4cb1-a8e4-ba5ae4cf928f.png)
![image](https://user-images.githubusercontent.com/43698511/129275005-a96ecebe-e64d-4b14-ba14-a485fb7478cd.png)
As you can see from the pictures . The elements of the nav should be displayed on a flex row. Kindly fix the issue

2021-08-12 22:03 UTC, safafa commented on style.css
> +}
- [ ] I think you forgot to change the CSS selector from h2 to h1 after making the changes in the HTML. This caused a small issue. Take a look at the pictures 
![image](https://user-images.githubusercontent.com/43698511/129275401-74395c71-89dd-4502-ba04-1e3674f55dfd.png)

![image](https://user-images.githubusercontent.com/43698511/129275430-2cea1307-5c51-4682-9c8f-68e40c391b1f.png)

Kindly fix the problem

2021-08-13 06:43 UTC, AbdumurodovaZulfizar approved these changes
Hello @Fikerte-T , I am @AbdumurodovaZulfizar, your reviewer for this project :wave:

## Status: PROJECT APPROVED 💫
#### Excellent job on this project guys. 🎆 Keep it up.

All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.

Congratulations on the splendid job ! 👍
You can now merge to master and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇

HAPPY CODING 💻

The review was done by @AbdumurodovaZulfizar
If there is anything that is not 💯% clear don't hesitate to hit me on:
[LinkedIn](https://www.linkedin.com/in/zulfizarabdumurodova/) | [Email](abdumurodovazulfizar77@gmail.com) | [Twitter](https://twitter.com/Zulfiza70357085)

2021-08-13 06:46 UTC, merged